### ISSUE TITLE
Support helm syntax

### ISSUE THREAD

**Issue by rolandmkunkel** [kevinjqiu/pat#18]
Are there any plans to add support for helm definitions as source for metrics? Currently when reading from a helm file with if-guards and apiVersion, kind, metadata and spec fields there is a parsing error with the error message 

` yaml: did not find expected node content `

It would also be nice to have better logging in case of reading from the fromFile is not successful.

**Comment by kevinjqiu** [comment]
helm syntax is just yaml with go template.  Since pat won't have those template variables so it can't render the template and then use the result yaml as input for the roles.

I suggest you run it through `helm template` first (so it generates a rendered template for the configmap) and then use something like `yq` to take the specific file content from the configmap.

Something like this:

`helm template /path/to/chart -x /path/to/configmap.yaml | yq .data.myrules` (replace myrules with the real filename in the rule configmap)
